namespace: tenant-alpha

resources:
- ../../../../base

# usage tenant specific helm chart
# helmCharts:
#  - name: prometheus
#    repo: https://prometheus-community.github.io/helm-charts
#    version: 14.3.0
#    releaseName: my-prometheus
#    namespace: tenant-aplha-monitoring

# usage tenant specific k8s objects
patches:
- target:
    kind: RoleBinding
    name: team-admin-rolebinding
  patch: |-
    - op: replace
      path: /subjects/0/name
      value: tenant-alpha-admin@mydomain.com
- target:
    kind: Namespace
    name: default
  patch: |-
    - op: replace
      path: /metadata/name
      value: tenant-alpha