# namespace: tenant-alpha

resources:
- ../../../../base

# helmCharts:
#  - name: cert-manager
#    repo: https://charts.jetstack.io
#    version: v1.7.0
#    releaseName: my-cert-manager
#    namespace: cert-manager
#  - name: prometheus
#    repo: https://prometheus-community.github.io/helm-charts
#    version: 14.3.0
#    releaseName: my-prometheus
#    namespace: monitoring

patches:
- target:
    kind: RoleBinding
    name: team-admin-rolebinding
  patch: |-
    - op: replace
      path: /subjects/0/name
      value: tenant-alpha-admin@mydomain.com
- target:
    kind: Namespace
    name: default
  patch: |-
    - op: replace
      path: /metadata/name
      value: tenant-alpha