resources:
- "helm-charts"
- "sector-optimus-prime/tenant-x"
- "sector-optimus-prime/tenant-y"
- "sector-optimus-prime/tenant-z"
- "sector-megatron/tenant-alpha"
- "sector-megatron/tenant-beta"
- "sector-megatron/tenant-gama"