# usage example for helm charts for an environment applicable to all Citi Sectors 
# this will be used for roll out of secutiry agents helm charts (Crowdstrike, tanium, qualis e.t.c)
helmCharts:
 - name: cert-manager
   repo: https://charts.jetstack.io
   version: v1.7.0
   releaseName: my-cert-manager
   namespace: cert-manager
 - name: prometheus
   repo: https://prometheus-community.github.io/helm-charts
   version: 14.3.0
   releaseName: my-prometheus
   namespace: monitoring