namespace: tenant-x

resources:
- ../../../../base

patches:
- target:
    kind: RoleBinding
    name: team-admin-rolebinding
  patch: |-
    - op: replace
      path: /subjects/0/name
      value: tenant-x-admin@mydomain.com
- target:
    kind: Namespace
    name: default
  patch: |-
    - op: replace
      path: /metadata/name
      value: tenant-x