helmCharts:
 - name: cert-manager
   repo: https://charts.jetstack.io
   version: v1.7.0
   releaseName: my-cert-manager
   namespace: cert-manager
 - name: prometheus
   repo: https://prometheus-community.github.io/helm-charts
   version: 14.3.0
   releaseName: my-prometheus
   namespace: monitoring